platform :ios, '16.0'

target 'Grandpax' do
  use_frameworks!

  pod 'RealmSwift', '10.43.0'
  pod 'SwiftLint'
end

target 'GrandpaxTests' do
  use_frameworks!

  pod 'RealmSwift', '10.43.0'
  pod 'SwiftLint'
end
