platform :ios, '9.0'

target 'Grandpax' do
  use_frameworks!

  # Pods for Grandpax
  pod 'RealmSwift'
  pod 'SwiftLint'
end

target 'GrandpaxTests' do
  use_frameworks!

  pod 'RealmSwift'
  pod 'SwiftLint'
end
